name: build

on: [push]

jobs:
  build_ubuntu:
    runs-on: ubuntu-24.04
    timeout-minutes: 6
    strategy:
      matrix:
        target: [ubuntu]
    steps:
      - name: Install GIT
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install
        run: |
          sudo apt-get install -y gcc-multilib g++-multilib linux-modules-extra-$(uname -r)
          python3 -m venv .venv && source ".venv/bin/activate"
          pip install -r requirements-dev.txt

      - name: Build SITL
        run: |
          source ".venv/bin/activate"
          make ${{ matrix.target }}-build

      - name: Run SITL and smoke test
        timeout-minutes: 3
        run: |
          ./scripts/vcan.sh slcan0
          source ".venv/bin/activate"
          make ${{ matrix.target }}-run &
          ./tests/smoke_socketcan.py
