name: code_style

on: [push]

jobs:
  cpplint:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v6
      - run: |
          pip3 install cpplint
          sudo apt-get install -y cppcheck dos2unix
      - run: make cpplint
